### ISSUE TITLE
Adding .env file with the variables did not work

### ISSUE THREAD

**Issue by debosmit-git** [yt2sp/yt2sp#2]
I had added the following in the .env file:
GOOGLE_CLIENTID = 'xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxx.apps.googleusercontent.com'
GOOGLE_APIKEY = 'xxxxxxxxxxx_Vqqbxxxxxxxxx'
SPOTIFY_CLIENTID = '7dxxxxxxxxxxxxxx2'

The popup of google did not launch login popup while Spotify said "IINVALID_CLIENT: Invalid redirect URI" in login popup.

Might be I am doing something wrong. A step by step guide would be helpful for having the  env variables.

**Comment by a-bali** [comment]
Looks like you did not set the correct redirect URI for your Spotify application. Check where you made the application to be accessible and set the proper callback URI in Spotify's development dashboard, as described e.g. [here](https://community.spotify.com/t5/Spotify-for-Developers/INVALID-CLIENT-Invalid-redirect-URI/td-p/5228936).
